# This file was generated by GoReleaser. DO NOT EDIT.
cask "ma" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "fc395619d12ade78ea4614baf7aea457791de9288b78420e6729e0975663443b"
      url "https://github.com/daaa1k/ma/releases/download/v#{version}/ma_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bb00bdfdb7af8813603236f338181dce9ae8a37320427be1f30313f797997bd3"
      url "https://github.com/daaa1k/ma/releases/download/v#{version}/ma_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "711e7196615cc837c11bbf0add57e3bb5cbd2a6a03e9fc67cce711a16100fe8b"
      url "https://github.com/daaa1k/ma/releases/download/v#{version}/ma_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "680e456ed42165cc57e520aa5a7a44b14f16869ba9a388685e70d60b63bc99a2"
      url "https://github.com/daaa1k/ma/releases/download/v#{version}/ma_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ma"
  desc "MCP config adapter and tool launcher for AI coding tools"
  homepage "https://github.com/daaa1k/ma"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ma"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ma"]
    end
  end

  # No zap stanza required

end
