# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdp" do
  name "mdp"
  desc "Paste clipboard image as Markdown link"
  homepage "https://github.com/daaa1k/mdp"
  version "0.3.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdp"

  on_macos do
    on_intel do
      url "https://github.com/daaa1k/mdp/releases/download/v#{version}/mdp_#{version}_darwin_amd64.tar.gz"
      sha256 "0757344f5c92a9dfe850edee5edf3b6e1cf05bbc7fa674891c422eb01b1052ff"
    end
    on_arm do
      url "https://github.com/daaa1k/mdp/releases/download/v#{version}/mdp_#{version}_darwin_arm64.tar.gz"
      sha256 "fa5723fb24c871939dfcda6d3da8250127f3441d693cccf2d8208ecede785a93"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/daaa1k/mdp/releases/download/v#{version}/mdp_#{version}_linux_amd64.tar.gz"
      sha256 "7f6d419640c2c87aa91a5dddfb00fe3efb6143e581fbc6f37c1df614219fdbea"
    end
    on_arm do
      url "https://github.com/daaa1k/mdp/releases/download/v#{version}/mdp_#{version}_linux_arm64.tar.gz"
      sha256 "a889432364ab6a588889f8d5fca4b43a2ef16cf95dd82fda6a179bea8a9298c5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdp"]
    end
  end

  # No zap stanza required
end
