# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdp" do
  name "mdp"
  desc "Paste clipboard image as Markdown link"
  homepage "https://github.com/daaa1k/mdp"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdp"

  on_macos do
    on_intel do
      url "https://github.com/daaa1k/mdp/releases/download/v#{version}/mdp_#{version}_darwin_amd64.tar.gz"
      sha256 "50436f0f8642aeed3f31cc5c07222e8172dbafb1a4e7c07a0a7fcd27601a1812"
    end
    on_arm do
      url "https://github.com/daaa1k/mdp/releases/download/v#{version}/mdp_#{version}_darwin_arm64.tar.gz"
      sha256 "c985bdde944fddc3675f4c21b27a2fdf3f3c25f97c9f1860bd92f25a13d093f8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/daaa1k/mdp/releases/download/v#{version}/mdp_#{version}_linux_amd64.tar.gz"
      sha256 "93e15813e560e04fe63cbe9e5f9e137fd4a7e457a122ab1ca0a441633901ac9a"
    end
    on_arm do
      url "https://github.com/daaa1k/mdp/releases/download/v#{version}/mdp_#{version}_linux_arm64.tar.gz"
      sha256 "a8d1223a904a4deab19184fd675290ba2fe8c72d1c7c2a1c81eb713692b029b8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdp"]
    end
  end

  # No zap stanza required
end
