# Generated by mdpz release CI. DO NOT EDIT manually.
cask "mdpz" do
  name "mdpz"
  desc "Paste clipboard image as Markdown link"
  homepage "https://github.com/daaa1k/mdpz"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdpz"

  on_macos do
    on_intel do
      url "https://github.com/daaa1k/mdpz/releases/download/v#{version}/mdpz_#{version}_darwin_amd64.tar.gz"
      sha256 "838b428cef303abcc675324428143cad3ed4575c3f52c5ec01fd5c4970401b13"
    end
    on_arm do
      url "https://github.com/daaa1k/mdpz/releases/download/v#{version}/mdpz_#{version}_darwin_arm64.tar.gz"
      sha256 "e839948061fc575922cf46122d41f66c1b02e669b50723fb563b64cf92543ae6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/daaa1k/mdpz/releases/download/v#{version}/mdpz_#{version}_linux_amd64.tar.gz"
      sha256 "5f0d2a9c56c19ca3196bfc57b9cb6ff13f9c1b022461a6bdceee192f2217a12c"
    end
    on_arm do
      url "https://github.com/daaa1k/mdpz/releases/download/v#{version}/mdpz_#{version}_linux_arm64.tar.gz"
      sha256 "e0ceae76320cbc7c1a8b0e5da9ae41419d6a6acacff8203debfabb1075dce6e8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdpz"]
    end
  end
end
