# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ma < Formula
  desc "MCP config adapter and tool launcher for AI coding tools"
  homepage "https://github.com/daaa1k/ma"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daaa1k/ma/releases/download/v0.1.7/ma_0.1.7_darwin_amd64.tar.gz"
      sha256 "cbf89ccba35b9cbd4b9c9f4547246d97e7477ffd538f250d2013a11ecd120fef"

      define_method(:install) do
        bin.install "ma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daaa1k/ma/releases/download/v0.1.7/ma_0.1.7_darwin_arm64.tar.gz"
      sha256 "35493c2545a78c80990336c102a5b4aab2b017b5bed80d756021f769692b96ce"

      define_method(:install) do
        bin.install "ma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daaa1k/ma/releases/download/v0.1.7/ma_0.1.7_linux_amd64.tar.gz"
      sha256 "070d399c6bd3458fd75e483295d5d403907cae6ddbdc079870f4e19d05a1feda"
      define_method(:install) do
        bin.install "ma"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daaa1k/ma/releases/download/v0.1.7/ma_0.1.7_linux_arm64.tar.gz"
      sha256 "2502d9e1400fa97c0b5c08eb174fb82d7bc5522520db05137f3adacaf6bea808"
      define_method(:install) do
        bin.install "ma"
      end
    end
  end

  test do
    system "#{bin}/ma", "--help"
  end
end
