# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdp < Formula
  desc "Paste clipboard image as Markdown link"
  homepage "https://github.com/daaa1k/mdp"
  version "0.2.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daaa1k/mdp/releases/download/v0.2.8/mdp_0.2.8_darwin_amd64.tar.gz"
      sha256 "c6851e6a3a564a6829b958b7d99fdb0a7d750fdc0c1a166fb77cbddfe3139c62"

      define_method(:install) do
        bin.install "mdp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daaa1k/mdp/releases/download/v0.2.8/mdp_0.2.8_darwin_arm64.tar.gz"
      sha256 "7421875734a923e62f3f76e6bd0b38a4aa466c2e384ed61a69f59ab915196f93"

      define_method(:install) do
        bin.install "mdp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daaa1k/mdp/releases/download/v0.2.8/mdp_0.2.8_linux_amd64.tar.gz"
      sha256 "99b6546739e62886b3a0ebf32c1fd9f3e1202470679ce84309f8842cdd622f10"
      define_method(:install) do
        bin.install "mdp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daaa1k/mdp/releases/download/v0.2.8/mdp_0.2.8_linux_arm64.tar.gz"
      sha256 "30fea0a14b73c0880f3bb004dc9ef5e88952002cd7bd4102e6a6e60fc5168988"
      define_method(:install) do
        bin.install "mdp"
      end
    end
  end

  test do
    system "#{bin}/mdp", "--help"
  end
end
