# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdp < Formula
  desc "Paste clipboard image as Markdown link"
  homepage "https://github.com/daaa1k/mdp"
  version "0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daaa1k/mdp/releases/download/v0.2.7/mdp_0.2.7_darwin_amd64.tar.gz"
      sha256 "2375f69158fb9c478f69c79ff1c39c5df0069c82d1e02fbb61321a115689c1b9"

      define_method(:install) do
        bin.install "mdp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daaa1k/mdp/releases/download/v0.2.7/mdp_0.2.7_darwin_arm64.tar.gz"
      sha256 "9015bf6a577aca19143187a59773a8cc6ce47947c5569e7c3364c16f998957e0"

      define_method(:install) do
        bin.install "mdp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daaa1k/mdp/releases/download/v0.2.7/mdp_0.2.7_linux_amd64.tar.gz"
      sha256 "ac1dfe180ce000b4c5ce5c3e8f6a5313f4efba98fe15aaa6f1b9d274829163d1"
      define_method(:install) do
        bin.install "mdp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daaa1k/mdp/releases/download/v0.2.7/mdp_0.2.7_linux_arm64.tar.gz"
      sha256 "dfbe1e2893870e906e59804c000404fd0883b41050dd0b7ac389a0f819e04b84"
      define_method(:install) do
        bin.install "mdp"
      end
    end
  end

  test do
    system "#{bin}/mdp", "--help"
  end
end
